apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-sa
  namespace: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stage-sa
  namespace: stage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-sa
  namespace: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-audit-sa
  namespace: rbac-audit
